CREATE TABLE REIMBURSEMENTS_STATUS(
REBURSESTATUSID INT PRIMARY KEY,
REBURSESTATUS VARCHAR(20));

CREATE TABLE REIMBURSEMENTS_TYPE(
REBURSETYPEID INT PRIMARY KEY,
REBURSETYPE VARCHAR(20));

CREATE TABLE REIMBURSEMENTS_ROLES(
REBURSEUSERROLEID INT PRIMARY KEY,
USERROLE VARCHAR(20)
);

DROP TABLE REIMBURSEMENTS;
DROP TABLE USERS;
DROP TABLE REIMBURSEMENTS_status;
DROP TABLE REIMBURSEMENTS_type;
DROP TABLE REIMBURSEMENTS_roles;


CREATE TABLE USERS(
USERID INT PRIMARY KEY,
USERNAME VARCHAR(30) UNIQUE,
UPASSWORD VARCHAR(30),
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
EMAIL VARCHAR(100) UNIQUE,
USERROLEID INT,
CONSTRAINT FK_USERROLE FOREIGN KEY (USERROLEID) REFERENCES
REIMBURSEMENTS_ROLES(REBURSEUSERROLEID)
);

-- Test out the SQL statements
SELECT * FROM users;
SELECT * FROM users WHERE username = 'employee';
SELECT * FROM reimbursements WHERE reburseid = '100';

SELECT * FROM reimbursements WHERE reburseauthor = 1;
UPDATE REIMBURSEMENTS SET REBURSERESOLVED = CURRENT_TIMESTAMP , REBURSESTATUSID = 2 WHERE reburseid = 10230 ;

INSERT INTO reimbursements VALUES(nextval('rebursesequence'),342,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Everthing was good',1,2,3,2);
SELECT * FROM reimbursements;

CREATE TABLE REIMBURSEMENTS(
REBURSEID INT PRIMARY KEY,
REBURSEAMOUNT FLOAT,
REBURSESUBMITTED TIMESTAMP,
REBURSERESOLVED TIMESTAMP,
REBURSEDESCRIPTION VARCHAR(1000),

REBURSEAUTHOR INT,
REBURSERESOLVER INT,
REBURSESTATUSID INT,
REBURSETYPEID INT,
CONSTRAINT FK_AUTHOR FOREIGN KEY (REBURSEAUTHOR) REFERENCES
USERS(USERID),

CONSTRAINT FK_RESOLVER FOREIGN KEY (REBURSERESOLVER) REFERENCES
USERS(USERID),

CONSTRAINT FK_STATUS_ID FOREIGN KEY (REBURSESTATUSID) REFERENCES
REIMBURSEMENTS_STATUS(REBURSESTATUSID),

CONSTRAINT FK_RETYPE_ID FOREIGN KEY (REBURSETYPEID) REFERENCES
REIMBURSEMENTS_TYPE(REBURSETYPEID)
);




--SEQUENCES--
DROP SEQUENCE rebursesequence;

CREATE SEQUENCE rebursesequence
START WITH 10000
INCREMENT by 10;

CREATE SEQUENCE statussequence
START WITH 100
INCREMENT by 1;

CREATE SEQUENCE typesequence
START WITH 100
INCREMENT by 1;

CREATE SEQUENCE usersequence
START WITH 1000
INCREMENT BY 100;

CREATE SEQUENCE rolesequence
START WITH 1000
INCREMENT BY 100;







INSERT INTO REIMBURSEMENTS_STATUS VALUES (1,'PENDING');
INSERT INTO REIMBURSEMENTS_STATUS VALUES (2,'APPROVED');
INSERT INTO REIMBURSEMENTS_STATUS VALUES (3,'DENIED');


INSERT INTO REIMBURSEMENTS_TYPE VALUES (1,'LODGING');
INSERT INTO REIMBURSEMENTS_TYPE VALUES (2,'TRAVEL');
INSERT INTO REIMBURSEMENTS_TYPE VALUES (3,'FOOD');
INSERT INTO REIMBURSEMENTS_TYPE VALUES (4,'OTHER');

INSERT INTO REIMBURSEMENTS_ROLES VALUES (1,'Employee');
INSERT INTO REIMBURSEMENTS_ROLES VALUES (2,'Finance Manager');

INSERT INTO USERS VALUES(
1,'employee','ilovemyjob','Nathanael','Williams','nathanael@gmail.com',
1);

INSERT INTO USERS VALUES(
2,'employee#2','ilovemyjob','Jane','Doe','janedoe@gmail.com',
1);

INSERT INTO USERS VALUES(
4,'employee#3','thisjobisthebest','Johnny','Deer',
'johnnydeer@gmail.com',1);

INSERT INTO USERS VALUES(
100,'manager','1234','Tim','Williams','timmy@gmail.com',
2);




